
"use client";
import PageHeader from '@/components/shared/page-header';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { FileUp, FileDown, History, ListChecks, Download, Trash2, AlertTriangle } from 'lucide-react';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { useToast } from '@/hooks/use-toast';
import { ChangeEvent, useState } from 'react';
import type { Panel, PanelEvent, PanelStatus } from '@/types/piv'; 
import { useData } from '@/contexts/data-provider';
import * as XLSX from 'xlsx';
import { format } from 'date-fns';
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from "@/components/ui/alert-dialog";

// Helper function to clean data from XLSX
function cleanExcelData(rawData: any[]): any[] {
  if (!rawData) return [];

  const cleanedData = rawData
    .map(row => {
      const cleanedRow: { [key: string]: any } = {};
      let hasData = false;
      for (const key in row) {
        if (Object.prototype.hasOwnProperty.call(row, key)) {
          const trimmedKey = key.trim(); // Trim key here
          if (!trimmedKey.startsWith("__EMPTY")) { // __EMPTY might be generated by XLSX for empty header cells
            const value = row[key];
            // Trim string values, pass others as is
            cleanedRow[trimmedKey] = typeof value === 'string' ? value.trim() : value;
            const finalValue = cleanedRow[trimmedKey];
            if (finalValue !== null && finalValue !== undefined && String(finalValue).trim() !== "") {
              hasData = true;
            }
          }
        }
      }
      return hasData ? cleanedRow : null;
    })
    .filter(row => row !== null);
  
  return cleanedData as any[];
}

// Mapeo de providerKey (camelCase, usado internamente) a posibles cabeceras del Excel (camelCase)
// La clave del mapa es la que usará el DataProvider internamente.
// El array de valores son las cabeceras exactas que se esperan en el Excel.
// Si Excel ya tiene cabeceras camelCase, el mapeo es directo.
const providerToExcelMap: { [providerKey: string]: string[] } = {
  // --- Campos Críticos / Identificadores ---
  'codigoParada': ['codigoParada'], // Clave camelCase, cabecera Excel camelCase
  // --- Fechas Principales PIV ---
  'fechaInstalacion': ['fechaInstalacion'],
  'fechaDesinstalacion': ['fechaDesinstalacion'],
  'fechaReinstalacion': ['fechaReinstalacion'],
  // --- Información de Facturación ---
  'importeMensual': ['importeMensual'], // Excel debe tener 'importeMensual'
  // --- Detalles de Ubicación y Estructura ---
  'municipioMarquesina': ['municipioMarquesina'],
  'direccion': ['direccion'], // Asumiendo 'direccion' como campo general.
  'direccionCce': ['direccionCce'], // Campo específico si existe
  // --- Detalles Técnicos y Administrativos del PIV ---
  'vigencia': ['vigencia'],
  'tipoPiv': ['tipoPiv'],
  'industrial': ['industrial'],
  'codigoMarquesina': ['codigoMarquesina'],
  'codigoPivAsignado': ['codigoPivAsignado'], // Añadido
  // --- Información Adicional y de Contrato ---
  'empresaConcesionaria': ['empresaConcesionaria'], // o 'cliente' si se prefiere unificar
  'ultimaInstalacionOReinstalacion': ['ultimaInstalacionOReinstalacion'],
  'observaciones': ['observaciones'], // o 'notas'
  'descripcionCorta': ['descripcionCorta'], // Añadido
  'op1': ['op1'],
  'op2': ['op2'],
  'marquesinaCce': ['marquesinaCce'],
  'cambioUbicacionReinstalacionesContrato2024_2025': ['cambioUbicacionReinstalacionesContrato2024_2025'],
  'reinstalacionVandalizados': ['reinstalacionVandalizados'],
  'garantiaCaducada': ['garantiaCaducada'],
  // Otros campos que puedan existir
  // 'notas': ['notas'], // Si 'observaciones' no es el campo principal para notas
  // 'cliente': ['cliente'], // Si 'empresaConcesionaria' no es el campo principal para cliente
};


function mapAndEnsureColumns(cleanedData: any[], type: 'initial' | 'monthly'): any[] {
  if (type === 'initial') {
    // Para la importación inicial, queremos pasar las claves tal como vienen del Excel
    // (asumiendo que ya son camelCase y limpias gracias a cleanExcelData)
    // y el DataProvider se encargará de mapear a la estructura Panel.
    // O, si queremos ser estrictos con las providerKey:
    return cleanedData.map(rowFromExcel => {
      const mappedRowForProvider: { [key: string]: any } = {};
      // Primero, copia todas las propiedades del Excel tal cual
      for (const excelHeader in rowFromExcel) {
        if (Object.prototype.hasOwnProperty.call(rowFromExcel, excelHeader)) {
           // Las claves ya están trimeadas por cleanExcelData
          mappedRowForProvider[excelHeader] = rowFromExcel[excelHeader];
        }
      }
      // Luego, asegura que las providerKeys definidas en providerToExcelMap existan,
      // tomando el valor de la primera cabecera de Excel candidata encontrada.
      // Esto es útil si una providerKey puede venir de varias cabeceras Excel.
      // Si el Excel ya tiene las claves camelCase deseadas, esto es redundante pero inofensivo.
      for (const providerKey in providerToExcelMap) {
        if (mappedRowForProvider[providerKey] === undefined) { // Solo si no se copió directamente
            let valueFound = undefined;
            for (const excelHeaderCandidate of providerToExcelMap[providerKey]) {
              if (Object.prototype.hasOwnProperty.call(rowFromExcel, excelHeaderCandidate)) {
                valueFound = rowFromExcel[excelHeaderCandidate];
                break; 
              }
            }
            mappedRowForProvider[providerKey] = valueFound;
        }
      }
      return mappedRowForProvider;
    });
  }
  // Para eventos mensuales, el mapeo es diferente y más simple (lo mantenemos)
  return cleanedData;
}


interface ColumnValidationResult {
  valid: boolean;
  missing: string[];
  available: string[];
}

function validateColumns(data: any[], type: 'initial' | 'monthly'): ColumnValidationResult {
  const availableKeys: string[] = (data && data.length > 0 && data[0]) ? Object.keys(data[0]) : [];

  let requiredHeaders: string[] = [];
  // Para la importación inicial, las cabeceras requeridas deben ser las camelCase que espera el DataProvider
  if (type === 'initial') {
    requiredHeaders = [
        "codigoParada", 
        "municipioMarquesina", // o la clave que uses para municipio
        "vigencia", 
        "fechaInstalacion",
        "importeMensual", // Asegúrate que esta columna exista en el Excel
        "empresaConcesionaria", // o la clave para cliente
        "direccion", // o la clave para dirección
    ]; 
  } else { 
    requiredHeaders = ["panelid", "fecha", "estado anterior", "estado nuevo"]; 
  }

  if (data.length === 0 && requiredHeaders.length > 0) {
     return { valid: false, missing: requiredHeaders, available: [] };
  }
  
  // Las claves en 'data' (que vienen de mappedData) ya deberían ser las camelCase.
  const missing = requiredHeaders.filter(reqHeader => {
    return !availableKeys.includes(reqHeader);
  });

  return {
    valid: missing.length === 0,
    missing,
    available: availableKeys, 
  };
}


export default function ImportExportPage() {
  const { toast } = useToast();
  const { importInitialData, clearAllPivData } = useData();
  const [isImporting, setIsImporting] = useState(false);
  const [isClearing, setIsClearing] = useState(false);
  const [showClearConfirm, setShowClearConfirm] = useState(false);


  const handleFileUpload = async (event: ChangeEvent<HTMLInputElement>, type: 'initial' | 'monthly') => {
    const file = event.target.files?.[0];
    if (!file) {
      toast({ title: "Ningún archivo seleccionado", variant: "destructive" });
      return;
    }

    if (!file.name.endsWith('.xlsx') && !file.name.endsWith('.xls')) {
       toast({ title: "Tipo de Archivo Inválido", description: "Por favor, sube un archivo Excel (.xlsx, .xls).", variant: "destructive" });
       return;
    }
    
    setIsImporting(true);
    toast({ title: "Procesando archivo...", description: `Importando ${file.name}. Por favor, espera.` });

    const reader = new FileReader();
    reader.onload = async (e) => {
      try {
        const arrayBuffer = e.target?.result;
        if (!arrayBuffer) {
          toast({ title: "Error de Lectura", description: "No se pudo leer el archivo.", variant: "destructive"});
          setIsImporting(false);
          if (event.target) event.target.value = '';
          return;
        }

        const workbook = XLSX.read(arrayBuffer, { type: 'array', cellDates: true }); 
        
        if (workbook.SheetNames.length === 0) {
          toast({ title: "Archivo Excel Vacío", description: "El archivo no contiene hojas.", variant: "destructive" });
          setIsImporting(false);
          if (event.target) event.target.value = '';
          return;
        }
        
        const sheetName = workbook.SheetNames[0];
        const worksheet = workbook.Sheets[sheetName];
        
        // Usar cabeceras de la fila 5 (range: 4), y obtenerlas tal cual.
        // header: 1 para obtener un array de arrays, luego procesar cabeceras manualmente
        // O usar la fila 5 directamente como cabeceras si sheet_to_json lo permite con `range`
        const rawJsonData = XLSX.utils.sheet_to_json(worksheet, { raw: false, range: 4, defval: null }) as any[];

        console.log("[Import Raw Excel Data] First 2 rows:", rawJsonData.slice(0,2));

        const cleanedData = cleanExcelData(rawJsonData);
        console.log(`[Import Cleaned Data] First 2 rows (keys: ${cleanedData.length > 0 ? Object.keys(cleanedData[0]).join(', ') : 'N/A'}):`, cleanedData.slice(0,2));
        
        // mapAndEnsureColumns ahora debería recibir datos con claves camelCase si el Excel las tiene.
        // Su propósito es más asegurar que las 'providerKey' esperadas estén presentes.
        const mappedData = mapAndEnsureColumns(cleanedData, type);
        console.log(`[Import Mapped Data for Provider] First 2 rows (keys: ${mappedData.length > 0 ? Object.keys(mappedData[0]).join(', ') : 'N/A'}):`, mappedData.slice(0,2));


        if (mappedData.length === 0 && type === 'initial') {
           toast({ 
            title: "Datos No Encontrados", 
            description: "No se encontraron datos procesables después de la limpieza y mapeo. Verifique el formato del archivo (cabeceras en fila 5, datos desde fila 6) y que contenga información válida.", 
            variant: "destructive",
            duration: 9000 
          });
          setIsImporting(false);
          if (event.target) event.target.value = '';
          return;
        } else if (mappedData.length === 0 && type === 'monthly') {
          toast({ 
            title: "Datos No Encontrados", 
            description: "No se encontraron eventos procesables después de la limpieza y mapeo. Verifique el formato del archivo y que contenga información válida.", 
            variant: "destructive",
            duration: 9000 
          });
          setIsImporting(false);
          if (event.target) event.target.value = '';
          return;
        }
        
        const columnValidation = validateColumns(mappedData, type);
        if (!columnValidation.valid) {
          const availableColsString = columnValidation.available.length > 0 ? columnValidation.available.join(', ') : 'Ninguna';
          const requiredColsString = columnValidation.missing.join(', ');
          let descriptionMessage = `Faltan columnas requeridas: ${requiredColsString}. `;
          descriptionMessage += `Columnas disponibles (después de mapeo a claves de DataProvider): ${availableColsString}. Verifique que el Excel contenga las cabeceras esperadas (camelCase).`;
          
          toast({
            title: `Error de Cabeceras Requeridas (${type === 'initial' ? 'Para DataProvider' : 'En Excel'})`,
            description: descriptionMessage,
            variant: "destructive",
            duration: 15000 
          });
          setIsImporting(false);
          if (event.target) event.target.value = '';
          return;
        }
        
        const result = await importInitialData(mappedData, type);


        if (result.success) {
          toast({ 
            title: "Importación Procesada", 
            description: `${result.message} Filas en archivo (después de limpieza): ${cleanedData.length}. Filas mapeadas para DataProvider: ${mappedData.length}. Paneles añadidos: ${result.addedCount || 0}. Eventos generados/añadidos: ${result.updatedCount || 0}. Omitidos: ${result.skippedCount || 0}.`,
            duration: 9000
          });
        } else {
          const errorMessages = result.errors && result.errors.length > 0 
            ? `Errores: ${result.errors.join('; ')}` 
            : 'Revisa el formato del archivo y los datos.';
          toast({ 
            title: "Falló la Importación", 
            description: `${result.message || 'Error desconocido.'} ${errorMessages}`, 
            variant: "destructive",
            duration: (result.errors && result.errors.length > 5 ? 15000 : 9000) 
          });
        }

      } catch (error: any) {
          console.error("Error en handleFileUpload:", error); 
          toast({ title: "Error de Importación", description: error.message || "Falló el procesamiento del archivo Excel.", variant: "destructive", duration: 9000 });
      } finally {
          setIsImporting(false);
          if (event.target) event.target.value = ''; 
      }
    };
    reader.onerror = () => {
        toast({ title: "Error de Lectura", description: "No se pudo leer el archivo seleccionado.", variant: "destructive"});
        setIsImporting(false);
        if (event.target) event.target.value = '';
    };
    reader.readAsArrayBuffer(file);
  };

  const handleExport = (dataType: 'panels' | 'events' | 'billing') => {
    if (dataType === 'panels') {
       alert(`Exportando todos los datos de paneles... (No implementado completamente)`);
    } else if (dataType === 'events') {
       alert(`Exportando historial completo de eventos... (No implementado completamente)`);
    } else if (dataType === 'billing') {
        alert(`Para exportar la vista actual de facturación, por favor usa el botón 'Exportar a Excel' en la página de Facturación Mensual.`);
    }
  };

  const handleClearData = async () => {
    setIsClearing(true);
    try {
      const result = await clearAllPivData();
      if (result.success) {
        toast({
          title: "Datos Eliminados",
          description: result.message || `Se eliminaron ${result.deletedCount} elementos.`,
        });
      } else {
        toast({
          title: "Error al Limpiar Datos",
          description: result.message || "No se pudieron eliminar los datos.",
          variant: "destructive",
        });
      }
    } catch (error: any) {
      toast({
        title: "Error Inesperado",
        description: error.message || "Ocurrió un error al limpiar los datos.",
        variant: "destructive",
      });
    } finally {
      setIsClearing(false);
      setShowClearConfirm(false);
    }
  };


  return (
    <div className="space-y-6">
      <PageHeader 
        title="Importar y Exportar Datos"
        description="Gestiona operaciones masivas de datos mediante archivos Excel."
      />

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        <Card className="shadow-lg">
          <CardHeader>
            <CardTitle className="flex items-center gap-2 font-headline"><FileUp className="text-primary"/>Importar Datos</CardTitle>
            <CardDescription>Importa datos de paneles PIV o cambios de estado mensuales desde archivos Excel.</CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            <div>
              <Label htmlFor="initial-data-file" className="text-sm font-medium">Importar Datos Iniciales de Paneles</Label>
              <Input id="initial-data-file" type="file" accept=".xlsx, .xls" className="mt-1" onChange={(e) => handleFileUpload(e, 'initial')} disabled={isImporting || isClearing} />
              <p className="text-xs text-muted-foreground mt-1">Importa datos de paneles. La fila 5 debe contener las cabeceras (camelCase) y los datos comenzar en la fila 6. Columnas requeridas: "codigoParada", "fechaInstalacion", etc.</p>
            </div>
            <hr/>
            <div>
              <Label htmlFor="monthly-events-file" className="text-sm font-medium">Importar Eventos Mensuales</Label>
              <Input id="monthly-events-file" type="file" accept=".xlsx, .xls" className="mt-1" onChange={(e) => handleFileUpload(e, 'monthly')} disabled={isImporting || isClearing} />
              <p className="text-xs text-muted-foreground mt-1">Registra todos los cambios de estado de los paneles. Columnas requeridas (case-insensitive): "panelid", "fecha", "estado anterior", "estado nuevo".</p>
            </div>
          </CardContent>
        </Card>

        <Card className="shadow-lg">
          <CardHeader>
            <CardTitle className="flex items-center gap-2 font-headline"><FileDown className="text-accent"/>Exportar Datos</CardTitle>
            <CardDescription>Exporta varios conjuntos de datos a Excel para análisis o copia de seguridad.</CardDescription>
          </CardHeader>
          <CardContent className="space-y-3">
            <Button onClick={() => handleExport('panels')} className="w-full justify-start" variant="outline" disabled={isImporting || isClearing}>
              <ListChecks className="mr-2 h-4 w-4" /> Exportar Todos los Datos de Paneles
            </Button>
            <Button onClick={() => handleExport('events')} className="w-full justify-start" variant="outline" disabled={isImporting || isClearing}>
              <History className="mr-2 h-4 w-4" /> Exportar Historial Completo de Eventos
            </Button>
            <Button onClick={() => handleExport('billing')} className="w-full justify-start" variant="outline" disabled={isImporting || isClearing}>
              <Download className="mr-2 h-4 w-4" /> Exportar Vista Actual de Facturación Mensual
            </Button>
          </CardContent>
        </Card>
      </div>

       <Card className="shadow-lg mt-6">
        <CardHeader>
            <CardTitle className="font-headline flex items-center gap-2"><Trash2 className="text-destructive"/>Acciones de Mantenimiento</CardTitle>
            <CardDescription>Operaciones para gestionar el estado general de los datos de la aplicación.</CardDescription>
        </CardHeader>
        <CardContent>
            <Button 
                variant="destructive" 
                onClick={() => setShowClearConfirm(true)} 
                disabled={isClearing || isImporting}
                className="w-full sm:w-auto"
            >
                <Trash2 className="mr-2 h-4 w-4" /> 
                {isClearing ? "Limpiando Datos..." : "Limpiar Todos los Datos PIV"}
            </Button>
            <p className="text-xs text-muted-foreground mt-2">
                <AlertTriangle className="inline-block h-3 w-3 mr-1 text-destructive" />
                ¡Atención! Esta acción eliminará permanentemente todos los paneles y eventos. Úselo con precaución, por ejemplo, antes de una reimportación completa.
            </p>
        </CardContent>
      </Card>

      <Card className="shadow-lg mt-6">
        <CardHeader>
            <CardTitle className="font-headline">Notas de Validación de Datos Durante la Importación (Datos Iniciales)</CardTitle>
        </CardHeader>
        <CardContent className="text-sm text-muted-foreground space-y-2">
            <p><strong>Formato de Archivo Excel:</strong> Cabeceras (camelCase) en Fila 5, datos desde Fila 6.</p>
            <p><strong>Lectura de Fechas:</strong> Se usa `cellDates:true`. La aplicación las formatea a `YYYY-MM-DD` para uso interno si son válidas.</p>
            <p><strong>Mapeo de Columnas:</strong> Las cabeceras del Excel (ej. `codigoParada`) se usan como claves en los datos procesados.</p>
            <p><strong>Columnas Requeridas:</strong> `codigoParada`, `municipioMarquesina`, `vigencia`, `fechaInstalacion`, `importeMensual`, `empresaConcesionaria`, `direccion`. Si faltan, la importación puede fallar.</p>
            <p><strong>Validación 'codigoParada':</strong> No puede estar vacío. Debe ser único.</p>
            <p><strong>Columna 'importeMensual':</strong> Si no existe o es inválida, se usa un valor por defecto (ej. 37.7).</p>
            <p><strong>Fechas PIV (`fechaInstalacion`, etc.):</strong> Cruciales. Si `fechaInstalacion` falta o es inválida, el panel podría no ser facturable. </p>
        </CardContent>
      </Card>

      <AlertDialog open={showClearConfirm} onOpenChange={setShowClearConfirm}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>¿Está absolutamente seguro?</AlertDialogTitle>
            <AlertDialogDescription>
              Esta acción es irreversible y eliminará permanentemente todos los datos de paneles y eventos de la aplicación.
              No podrá recuperar estos datos. ¿Desea continuar?
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel onClick={() => setShowClearConfirm(false)} disabled={isClearing}>Cancelar</AlertDialogCancel>
            <Button variant="destructive" onClick={handleClearData} disabled={isClearing}>
              {isClearing ? "Eliminando..." : "Sí, eliminar todos los datos"}
            </Button>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>

    </div>
  );
}
